name: Despliegue Sonarqube con Openshift

on:
  workflow_dispatch:


jobs:
  sonarqube-openshift:

    runs-on: ubuntu-latest
  
    steps:
    - name: Install ibmcloud 
      run: |
        curl -fsSL https://download.clis.cloud.ibm.com/ibm-cloud-cli/2.31.0/IBM_Cloud_CLI_2.31.0_amd64.tar.gz -o ibm-cloud-cli.tar.gz
        tar -xvzf ibm-cloud-cli.tar.gz && rm ibm-cloud-cli.tar.gz
        cd Bluemix_CLI
        sudo ./install
    
    - name: Install plugin OC on IBM CLI
      run: ibmcloud plugin install ks

    - name: Login to IBM
      run: |
        ibmcloud login --apikey ${{secrets.API_KEY_IBM}} --no-region
        ibmcloud oc cluster get --cluster ez-ibm-openshift-vpc-6zmu
    
    - name: Install Kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" 
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        kubectl version --client

    - name: modified kubeconfig
      run: ibmcloud ks cluster config --cluster ez-ibm-openshift-vpc-6zmu --admin

    - name: Install Helm
      run: |
        sudo curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
        sudo apt-get install apt-transport-https --yes
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install helm

    - name: Crear namespace si no esta creado anteriormente
      run: |
        if ! kubectl get ns sonarqube > /dev/null 2>&1; then
          kubectl create ns sonarqube
        fi
    
    - name: Sacar Dominio para posterior introducion en values del chart
      id: domain-step
      run: |
        echo "dominio=$(ibmcloud oc cluster get --cluster ez-ibm-openshift-vpc-6zmu | grep "Ingress Subdomain:" | sed 's/.*Ingress Subdomain:[[:space:]]*//')" >> $GITHUB_OUTPUT
    - name: Checkout code
      uses: actions/checkout@v3
    - name: anyadir librerias y desplegar helm
      run: |
        pwd
        ls -la
        helm repo add sonarqube https://SonarSource.github.io/helm-chart-sonarqube
        helm install my-sonarqube sonarqube/sonarqube --namespace sonarqube -f values-sonar.yaml --set Openshift.route.host=sonar-default.${{steps.domain-step.outputs.dominio}}
      working-directory: chart/sonarqube
    
